In [1]:
import qcdenoise

### 0.Define noise specs (for unitary noise model) and circuit specs

In [2]:
noise_specs = {'type':'phase_amplitude_damping_error', 'max_prob': 0.35} # noise_specs=None gives ideal circuit sampling

# circuit stuff
n_qubits = 5
ghz = qcdenoise.GHZCircuit # redundant- qcdenoise.GHZ is the default CircuitConstructor

# setup the circuit sampler w/ Unitary noise model
sampler = qcdenoise.UnitaryNoiseSampler(noise_specs=noise_specs, circuit_builder=ghz, 
                                        n_qubits=n_qubits)

Using Circuit GHZ
Using Unitary Noise Model (phase_amplitude_damping_error)


### 1. Sample the circuit and get dictionary of all possible outcomes

In [3]:
# 1. Sample the circuit and get dictionary of all possible outcomes
counts = sampler.sample(counts=True)

# filter counts to avoid plotting 2**n_qubits
_ = [counts.pop(key) for key in list(counts.keys()) if counts[key] < 5e-3]

counts

(array([0.15320471, 0.2748755 ]), [0, 0])
(array([0.27299153, 0.09540741]), [0, 0])
(array([0.09676249, 0.28065526]), [0, 0])


{'00000': 0.517578125,
 '00001': 0.0625,
 '00010': 0.021484375,
 '00011': 0.0830078125,
 '00111': 0.0078125,
 '01110': 0.0068359375,
 '01111': 0.013671875,
 '10110': 0.0205078125,
 '10111': 0.05859375,
 '11100': 0.005859375,
 '11101': 0.0166015625,
 '11110': 0.0498046875,
 '11111': 0.1279296875}

### 2. Repeated Sampling  
For each sample:  
1. new random circuit is built.
2. new noise model: random unitary noise channels are inserted
3. the circuit is executed along with the noise model

In [4]:
for i in range(10):
    print("Sample %d:" %i)
    prob = sampler.sample() # return a numpy array instead of counts- this is more convenient for parallel sampling
    print("Probability Vector: ", prob)
    adjT = sampler.get_adjacency_tensor() # get the adjacency tensor
    print("Adjacency Tensor: ", adjT)

Sample 0:
Probability Vector:  [[0.48535156 0.48535156]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.51464844 0.51464844]]
Using noise model basis gates in transpilation.
Adjacency Tensor:  [[[4. 1. 0. 0. 0.]
  [1. 0. 1. 0. 0.]
  [0. 1. 0. 1. 0.]
  [0. 0. 1. 0. 1.]
  [0. 0. 0. 1. 0.]]

 [[0

### 3. Graph Circuit Constructor. 
Same as above, except will use a graph circuit builder


In [5]:
graph_circ = qcdenoise.GraphCircuit # qcdenoise.GHZ is the default circuit is qcdenoise.UnitaryNoiseSampler

# setup the circuit sampler w/ Unitary noise model
sampler = qcdenoise.UnitaryNoiseSampler(noise_specs=noise_specs, circuit_builder=graph_circ, 
                                        n_qubits=n_qubits, verbose=True)

Using Circuit GraphState
Using Unitary Noise Model (phase_amplitude_damping_error)


#### Sampling

In [6]:
# 1. Sample the circuit and get dictionary of all possible outcomes
counts = sampler.sample(counts=True)

# filter counts to avoid plotting 2**n_qubits
# _ = [counts.pop(key) for key in list(counts.keys()) if counts[key] < 5e-3]

counts

Configuration with 1 Subgraphs with # nodes:(5,)
Assigning a Stochastic Controlled Phase Gate (H-CNOT-P(U)-H) to Node Edges
(array([0.23154064, 0.31019134]), [0, 0])
(array([0.23491176, 0.11538828]), [0, 0])
(array([0.07257663, 0.00407123]), [0, 0])


{'00000': 0.0224609375,
 '00001': 0.0517578125,
 '00010': 0.0400390625,
 '00011': 0.0087890625,
 '00100': 0.0478515625,
 '00101': 0.015625,
 '00110': 0.0107421875,
 '00111': 0.03515625,
 '01000': 0.044921875,
 '01001': 0.013671875,
 '01010': 0.0166015625,
 '01011': 0.052734375,
 '01100': 0.0146484375,
 '01101': 0.0634765625,
 '01110': 0.0419921875,
 '01111': 0.0107421875,
 '10000': 0.052734375,
 '10001': 0.0048828125,
 '10010': 0.021484375,
 '10011': 0.041015625,
 '10100': 0.021484375,
 '10101': 0.044921875,
 '10110': 0.0498046875,
 '10111': 0.0146484375,
 '11000': 0.0166015625,
 '11001': 0.0546875,
 '11010': 0.0537109375,
 '11011': 0.0078125,
 '11100': 0.044921875,
 '11101': 0.01171875,
 '11110': 0.01953125,
 '11111': 0.048828125}

In [7]:
for i in range(10):
    print("Sample %d:" %i)
    prob = sampler.sample() # return a numpy array instead of counts- this is more convenient for parallel sampling
    print("Probability Vector: ", prob)
    adjT = sampler.get_adjacency_tensor() # get the adjacency tensor
    print("Adjacency Tensor: ", adjT)

Sample 0:
Configuration with 1 Subgraphs with # nodes:(5,)
Assigning a Stochastic Controlled Phase Gate (H-CNOT-P(U)-H) to Node Edges
(array([0.34294386, 0.24150567]), [0, 0])
(array([0.34670119, 0.24168701]), [0, 0])
(array([0.33184313, 0.20427563]), [0, 0])
Probability Vector:  [[0.25       0.23242188]
 [0.28320312 0.25878906]
 [0.0390625  0.        ]
 [0.03710938 0.        ]
 [0.00976562 0.        ]
 [0.01757812 0.        ]
 [0.02246094 0.        ]
 [0.01660156 0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.0234375  0.        ]
 [0.02148438 0.        ]
 [0.04003906 0.        ]
 [0.04785156 0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.01367188 0.        ]
 [0.01074219 0.        ]
 [0.02148438 0.        ]
 [0.02050781 0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.02441406 0.    

#### 4. Parallel Sampling  
w/ multiprocessing. We use the helper functions in qcdenoise.circuit_sampling_utils.  
Sampler and circuit builders are specified as before, except the class instantiation is done by each process in its local address space.

In [11]:
from qcdenoise import parallel_sampler_prob, UnitaryNoiseSampler, GHZCircuit

see `parallel_circuit_sampling.py` for the script executed below

In [14]:
!python parallel_circuit_sampling.py

Round= 0
PID: 85976, Sample #: 0
PID: 85977, Sample #: 0
PID: 85977, Sample #: 10
PID: 85976, Sample #: 10
Round= 1
PID: 85978, Sample #: 0
PID: 85979, Sample #: 0
PID: 85979, Sample #: 10
PID: 85978, Sample #: 10
Round= 2
PID: 85981, Sample #: 0
PID: 85980, Sample #: 0
PID: 85980, Sample #: 10
PID: 85981, Sample #: 10
Round= 3
PID: 85982, Sample #: 0
PID: 85983, Sample #: 0
PID: 85982, Sample #: 10
PID: 85983, Sample #: 10
Round= 4
PID: 85984, Sample #: 0
PID: 85985, Sample #: 0
PID: 85984, Sample #: 10
PID: 85985, Sample #: 10
Round= 5
PID: 85986, Sample #: 0
PID: 85987, Sample #: 0
PID: 85986, Sample #: 10
PID: 85987, Sample #: 10
Round= 6
PID: 85989, Sample #: 0
PID: 85988, Sample #: 0
PID: 85988, Sample #: 10
PID: 85989, Sample #: 10
Round= 7
PID: 85991, Sample #: 0
PID: 85990, Sample #: 0
PID: 85991, Sample #: 10
PID: 85990, Sample #: 10
Round= 8
PID: 85992, Sample #: 0
PID: 85993, Sample #: 0
PID: 85993, Sample #: 10
PID: 85992, Sample #: 10
Round= 9
PID: 85994, Sample #: 0
PID: